### ISSUE TITLE
What is CC3M Embeddings

### ISSUE THREAD

**Issue by ziqipang** [kohjingyu/fromage#27]
Thank you for your great work and help previously!

I am trying to run the evaluation of `evals/eval_vist_retrieval.py` and noticed that its prerequisite is having the cc3m embeddings prepared. I am wondering: (1) what's the function of this embedding file, and, (2) if I finetune the Fromage model differently, do I need to generate a new embedding file, and if so, could you please release the code for this part?

Thank you again for your time and attention! Greatly appreciate it!

**Comment by kohjingyu** [comment]
> what's the function of this embedding file

These are [precomputed embeddings for a list of URLs from CC3M](https://github.com/kohjingyu/fromage#precomputed-embeddings-for-image-retrieval).

> if I finetune the Fromage model differently, do I need to generate a new embedding file, and if so, could you please release the code for this part

You don't necessarily need to if you just want to run the evals, since the retrieval is [done over VIST images](https://github.com/kohjingyu/fromage/blob/34a7d9bc3e26636c79beda53068e89d946d74480/evals/eval_vist_retrieval.py#L55-L57) and not CC3M. You can bypass this by using just the same cc3m file we provide, it should not affect the eval scripts.

This is mostly just for qualitative results (in the inference notebook, the output images are retrieved from the candidate images in the `cc3m_embeddings.pkl` file). If you want to do so for your new model, I've uploaded the (untested) script [here](https://github.com/kohjingyu/fromage/blob/34a7d9bc3e26636c79beda53068e89d946d74480/fromage/extract_img_embs.py). You will need to replace the list of URLs in that file with the URLs that you want to retrieve images from.

**Comment by ziqipang** [comment]
@kohjingyu Thank you! It is nice to know that these are similar to place holders and won't affect the evaluation. I will check out the code and update you if any issues occur.
